apiVersion: apps/v1
kind: Deployment
metadata:
  name: warehouse
spec:
  selector:
    matchLabels:
      app: warehouse
  template:
    metadata:
      labels:
        app: warehouse
    spec:
      containers:
      - name: warehouse
        image: warehouse
        imagePullPolicy: Never
        resources:
          limits:
            memory: "512Mi"
            cpu: "1000m"
        ports:
        - containerPort: 8081
